# ECE 2112_PA2

Name: Milan, Rye Keane Lorenzo H.

Section: 2ECE-D

**Reproducible Normalization Problem**

In [37]:
import numpy as np

In [38]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))
mean = np.mean(X)
std = np.std(X)

X_normalized = (X-mean)/std


print("Original Array X:\n", X)
print("\nNormalized Array X:\n", X_normalized)
print("\nMean of normalized array:", X_normalized.mean())
print("\nStandard deviation of normalized array:", X_normalized.std())
np.save('X_normalized.npy', X_normalized)

Original Array X:
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

Normalized Array X:
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

Mean of normalized array: 0.0

Standard deviation of normalized array: 0.9999999999999999


**Cubes Divisible by 4 Problem**

In [39]:
C = np.power(np.arange (1,101), 3).reshape(10, 10)
C

div_by_4 = C[np.mod(C, 4) == 0]
div_by_4

print("Shape of Array C:", C.shape)
print("\nElements divisible by 4:\n", div_by_4)
print("\nNumber of selected elements:", div_by_4.size)
np.save('div_by_4.npy', div_by_4)

Shape of Array C: (10, 10)

Elements divisible by 4:
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

Number of selected elements: 50


**Above-Mean Squares Problem**

In [41]:
S = np.power(np.arange (1,37), 2).reshape(6, 6)
S

S_mean = np.mean(S)
above_mean = S[S>S_mean]
print("Array S:\n", S)
print("\nElements above the mean:\n", above_mean)
print("\nNumber of selected elements:", above_mean.size)
print("\nMean of S:", S_mean)
np.save('above_mean.npy', above_mean)

Array S:
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

Elements above the mean:
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

Number of selected elements: 15

Mean of S: 450.1666666666667
